USE ahab_db;

DROP TABLE IF EXISTS log;

DROP TABLE IF EXISTS overview;

DROP TABLE IF EXISTS system;

DROP TABLE IF EXISTS system_status;

DROP TABLE IF EXISTS sensor_unit;

DROP TABLE IF EXISTS control_unit;

DROP TABLE IF EXISTS deep_system;

DROP TABLE IF EXISTS scu;

DROP TABLE IF EXISTS sensor;

DROP TABLE IF EXISTS hv_card;

DROP TABLE IF EXISTS laser;

DROP TABLE IF EXISTS leica_cam;

DROP TABLE IF EXISTS receiver_chip;